//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTLogistics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int IDNumber { get; set; }
        public string PostalAddress { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string Comments { get; set; }
        public int UserRoleId { get; set; }
        public System.DateTime DatOfBirth { get; set; }
        public int CellPhone { get; set; }
    
        public virtual UserRole UserRole { get; set; }
    }
}
