//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTLogistics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderHistories = new HashSet<OrderHistory>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<OrderHistory> OrderHistories { get; set; }
    }
}
